qodo-ai/pr-agent

pr_agent/algo/utils.py
pr_agent/settings/pr_reviewer_prompts.toml
tests/unit/test_convert_to_markdown.py
tests/unit/test_fix_output.py
tests/unit/test_parse_code_suggestion.py

remove suggestion number from prompt

remove suggestion number

---

Dockerfile.github_action_dockerhub
action.yaml
pr_agent/servers/github_action_runner.py
pr_agent/tools/pr_reviewer.py

Type of PR:
___
**This PR enhances the functionality of the Github Action runner by improving error handling and logging. It also updates the Dockerfile reference in the action.yaml file.**
___
- `pr_agent/servers/github_action_runner.py`: Added error handling for JSON parsing and logging for unknown commands. Removed the check for 'RUNNER_DEBUG' environment variable.
- `Dockerfile.github_action_dockerhub`: New file added, which is a Dockerfile for the Github Action.
- `action.yaml`: Updated the Dockerfile reference to 'Dockerfile.github_action_dockerhub'.

Enhancement: Apply Github Action

---

README.md

Type of PR:
___
**This PR updates the README.md file with new GIFs demonstrating the functionality of the tool. It also includes minor text corrections and improvements in the documentation.**
___
-`README.md`: The file has been updated with new GIFs to better demonstrate the tool's functionality. Minor text corrections have been made throughout the document, including proper capitalization of 'GitHub', punctuation fixes, and improved phrasing. The sections on running the tool as a GitHub Action and GitHub App have been updated for clarity. The 'Usage and Tools' section has been revised for better readability.

Update README with new GIFs and minor text corrections

---

README.md

Type of PR:
___
**This PR corrects the spelling of 'GitHub' in the README.md file. The previous version had 'Github', which has been updated to the correct form 'GitHub'.**
___
- `README.md`: Corrected the spelling of 'GitHub' in various sections of the document.

Minor Spelling Fix

---

pr_agent/git_providers/gitlab_provider.py

In case of new file creation by the MR there is a 404 error on file retrieval by gitlab provider.
It was handled by catching the error and replacing the file string with an empty string. Type checking was added before byte decoding - necessary in case of the empty string.

Fixes 404 error on gitlab file provider happening in case a MR introduced a new file.

---

README.md
pr_agent/algo/pr_processing.py
pr_agent/git_providers/github_provider.py
pr_agent/git_providers/gitlab_provider.py
pr_agent/tools/pr_reviewer.py

Type of PR:
___
**This PR includes several refactoring changes to the Git providers and PR processing logic. The changes aim to improve code readability and maintainability, and to fix minor issues in the code.**
___
-`pr_agent/algo/pr_processing.py`: Refactored the way diff files are fetched and used in the PR processing logic.
-`pr_agent/git_providers/github_provider.py`: Updated the logic for publishing inline comments and finding relevant lines in the diff files. The '+' symbol added by the model to the beginning of the relevant line is now properly handled.
-`pr_agent/git_providers/gitlab_provider.py`: Implemented the method for publishing PR descriptions in GitLab, which was previously not implemented. Also, updated the …

Support describe for Gitlab 

---

README.md
pr_agent/algo/language_handler.py
pr_agent/algo/pr_processing.py
pr_agent/git_providers/github_provider.py
pr_agent/git_providers/gitlab_provider.py
pr_agent/tools/pr_reviewer.py

Filter out bad files before getting their head and original source code and diff

Filter out bad files before getting their head and original source code and diff

---

pr_agent/algo/utils.py
pr_agent/tools/pr_reviewer.py

Type of PR:
**Bug fix**
___
**This PR introduces two main changes. First, it adds a new category 'Insights from user's answers' to the markdown output. Second, it fixes a bug in the user answers fetching process in the PR reviewer tool.**
___
- `pr_agent/algo/utils.py`: A new category 'Insights from user's answers' has been added to the markdown output dictionary. 
- `pr_agent/tools/pr_reviewer.py`: Fixed a bug where the user answers fetching process was incorrectly fetching a single string instead of a tuple containing both the answer and question strings.

Add Insights from User's Answers and Fix User Answers Fetching

---

pr_agent/cli.py

Type of PR:
___
**This PR modifies the 'run' function in 'cli.py' to accept arguments, allowing for more flexible usage of the command line interface. The argument parsing is now done inside the function, using the provided arguments, instead of directly parsing the command line arguments. This change will make it easier to use the function programmatically in other parts of the code.**
___
- `cli.py`: The 'run' function now accepts an 'args' parameter, which is used for argument parsing. The 'args' parameter defaults to None, and if no arguments are provided, the function will behave as before, parsing the command line arguments. The 'args' parameter is passed to the 'argparse.ArgumentParser.parse_args' method.

CLI Arguments Refactoring

---

INSTALL.md
docker/Dockerfile.lambda
pr_agent/servers/serverless.py

Type of PR:
___
**This PR introduces the ability to deploy the application as a serverless function on AWS Lambda. It includes the necessary changes in the codebase and updates the installation documentation to guide users through the process of deploying the application on AWS Lambda.**
___
- `pr_agent/servers/serverless.py`: This new file is added to handle the serverless deployment. It sets up a FastAPI application and uses the Mangum adapter to create an AWS Lambda handler.
- `INSTALL.md`: This file is updated to include instructions for deploying the application on AWS Lambda. It guides the user through the process of building a Docker image, pushing it to AWS ECR, and setting up a Lambda function.
- …

Deployment on AWS Lambda

---

pr_agent/algo/ai_handler.py
pr_agent/algo/git_patch_processing.py
pr_agent/algo/pr_processing.py
pr_agent/algo/token_handler.py
pr_agent/algo/utils.py

PR Type:
___
**This pull request focuses on adding docstrings to various Python files in the project. The docstrings provide a brief description of the purpose of each function and class, and detail the input parameters and return types/values. This will improve code readability and maintainability, and provide better support for developers and users of the project.**
___
-`ai_handler.py`: Added docstrings to the AiHandler class, its constructor, and the chat_completion method.
-`git_patch_processing.py`: Added docstrings to the extend_patch, omit_deletion_hunks, handle_patch_deletions, and convert_to_hunks_with_lines_numbers functions.
-`pr_processing.py`: Added docstrings to the get_pr_diff, pr_generate_extended_diff, and …

Adding Docstrings to Python Files

---

pr_agent/cli.py

PR Type:
___
**This pull request refactors the way CLI commands are handled in the 'pr_agent/cli.py' script. The changes aim to improve code readability and maintainability by replacing a series of if-elif statements with a dictionary that maps commands to their corresponding handler functions.**
___
-`pr_agent/cli.py`: The main changes in this file involve the refactoring of the 'run' function. Instead of using a series of if-elif statements to handle different commands, a dictionary named 'commands' has been introduced. This dictionary maps command names to their corresponding handler functions. Each command now has a dedicated function that handles its execution. This change improves the readability and maintainability of the …

Refactoring CLI Commands Handling

---

README.md

PR Type:
___
**This PR updates the GIFs in the README file. The source of the GIFs has been changed to a new location on the same domain. Additionally, a new GIF has been added to demonstrate the 'reflect and review' functionality.**
___
-`README.md`: The GIFs demonstrating the '/describe', '/review', '/ask', and '/improve' functionalities have been updated with new source URLs. A new GIF demonstrating the 'reflect and review' functionality has been added. The GIF showing the review generation process has also been updated with a new source URL.

Update README GIFs

---

INSTALL.md

PR Type:
___
**This PR updates the installation instructions in the README file. The changes include adding the pr_agent folder to the PYTHONPATH and running the cli.py script.**
___
- `INSTALL.md`: The installation instructions have been updated. The user is now instructed to add the pr_agent folder to their PYTHONPATH and then run the cli.py script. The previous instructions to run Python scripts from the scripts folder have been removed.

Update Installation Instructions in README

---

pr_agent/git_providers/github_provider.py

PR Type:
___
**This PR optimizes the way code suggestions are published in the PR. Instead of making an API call for each suggestion, all suggestions are now sent in a single API call. This reduces the number of API calls and thus improves performance.**
___
-`github_provider.py`: The method `publish_code_suggestions` has been refactored. The loop that iterates over code suggestions now only prepares the parameters for the API call. The API call itself is made after the loop, sending all code suggestions in a single request. The commit id is no longer explicitly set in the parameters, as it's already included in the `create_review` method call. The import statement for `github.PullRequestComment` and the related code have been …

Optimize Code Suggestions API Calls

---

README.md

PR Type:
___
**This PR updates the URLs of the GIFs used in the README file. The GIFs have been moved from a previous location to a new one, and the URLs have been updated to reflect this change.**
___
- `README.md`: The URLs of the GIFs demonstrating the functionality of the tool have been updated. Also, the command '/reflect and review:' has been renamed to '/reflect_and_review:'.

Update GIF URLs in README

---

pr_agent/servers/github_action_runner.py
pr_agent/tools/pr_description.py

PR Type:
___
**This PR introduces improvements in the code of the PR Agent. It includes better handling of environment variables, improved error handling, and code documentation in the 'github_action_runner.py' and 'pr_description.py' files.**
___
- `pr_agent/servers/github_action_runner.py`: The environment variables are now fetched without a default value. The error handling for missing environment variables has been improved. The loading of the event payload has been moved to a separate section. The handling of pull request and issue comment events has been improved.
- `pr_agent/tools/pr_description.py`: The PRDescription class has been thoroughly documented. The methods '_prepare_prediction' and '_get_prediction' now have …

Code Enhancement in PR Agent

---

pr_agent/algo/language_handler.py
pr_agent/config_loader.py
pr_agent/git_providers/__init__.py
pr_agent/git_providers/local_git_provider.py
pr_agent/settings/configuration.toml
requirements.txt

PR Type:
___
**This PR introduces support for local git repositories in the PR Agent. It implements a new LocalGitProvider class that mimics the functionality of the GitProvider interface for local repositories. This allows users to generate diff-patches from local branches without requiring a hosted git repository. The PR also includes changes to the configuration settings to accommodate this new feature.**
___
-`pr_agent/algo/language_handler.py`: Added a check to ensure filename is not None before validating file extensions.
-`pr_agent/config_loader.py`: Added functions to find the repository root and pyproject.toml file. The settings are now loaded from the pyproject.toml file if it exists. …

Add Local Git Provider Support

---

pr_agent/servers/github_app.py
pr_agent/servers/github_polling.py

PR Type:
___
**This pull request includes refactoring of the GitHub webhook and polling server. The changes mainly focus on improving code readability, adding type hints, and enhancing error handling. Also, the PR includes the addition of docstrings for better understanding of the functions and their roles.**
___
-`pr_agent/servers/github_app.py`: This file has been refactored to improve code readability and error handling. Type hints have been added to function parameters for better type safety. Docstrings have been added to functions to provide a better understanding of their roles. The error handling has been improved by using the `getattr` function instead of a try-except block to get the `webhook_secret`. The logic of the …

Enhancement of GitHub Webhook and Polling Server

---

pr_agent/tools/pr_reviewer.py

PR Type:
___
**This pull request focuses on enhancing the PRReviewer class in pr_reviewer.py. It includes adding type hints to function signatures, improving the docstrings for better understanding of the methods, and refactoring some parts of the code for better readability and maintainability.**
___
-`pr_agent/tools/pr_reviewer.py`: This file has been extensively updated. The PRReviewer class has been enhanced with better docstrings and type hints. The methods within this class have been refactored for better readability and maintainability. Some methods have been updated to improve the process of generating AI predictions and preparing PR reviews. The method for publishing inline code comments has also been updated.

Enhancement of PRReviewer class in pr_reviewer.py

---

pr_agent/git_providers/local_git_provider.py

PR Type:
___
**This PR introduces several improvements to the LocalGitProvider class. It now raises an error if the repository root cannot be found, and the PR title is now derived from the head branch name instead of the target branch name.**
___
-`local_git_provider.py`: Added a check in the constructor to raise an error if the repository root cannot be found. Changed the `get_pr_title` method to return the head branch name instead of the target branch name.

Improvements to Local Git Provider

---

CHANGELOG.md
README.md

PR Type:
___
**This PR adds a new section to the README file, titled 'Why use PR-Agent?'. The section provides reasons and justifications for using the PR-Agent tool, highlighting its unique features and benefits.**
___
-`README.md`: A new section 'Why use PR-Agent?' has been added. This section explains the benefits and unique features of PR-Agent, such as its real-life practical usage, PR compression strategy, JSON prompting strategy, support for multiple git providers, and its open-source nature.

Update README with 'Why use PR-Agent?' section

---

pr_agent/algo/pr_processing.py
pr_agent/git_providers/git_provider.py
pr_agent/git_providers/github_provider.py
pr_agent/servers/utils.py
pr_agent/settings/configuration.toml

PR Type:
___
**This PR introduces handling for the RateLimitExceededException from the GitHub API. It adds a retry mechanism for the get_diff_files method in the GithubProvider class and logs an error message when the rate limit is exceeded. Additionally, a new custom exception, RateLimitExceeded, is introduced in the servers/utils.py file. The PR also includes a new configuration setting for the number of retries when the rate limit is exceeded.**
___
-`pr_agent/algo/pr_processing.py`: Added exception handling for RateLimitExceededException when calling get_diff_files method from the git provider.
-`pr_agent/git_providers/github_provider.py`: Added a retry mechanism for the get_diff_files method and raised a custom exception, …

Handling GitHub API Rate Limit Exceeded Exception

---

PR_COMPRESSION.md

Fix typo in PR_COMPRESSION.md

---

CHANGELOG.md
pr_agent/git_providers/gitlab_provider.py
pr_agent/tools/pr_code_suggestions.py

PR Type:
**Bug fix**
___
**This PR introduces several improvements and error handling mechanisms in the GitLab provider. It includes better logging, handling of code suggestions, and error handling in case of exceptions. Also fixed a major bug - additional unneeded line was added to code suggestion in GitLab**
___
-`git_providers/gitlab_provider.py`: The changes in this file mainly focus on improving the handling of inline comments and code suggestions. A logging statement has been added for debugging purposes. The code for publishing code suggestions has been wrapped in a try-except block to handle any exceptions that may occur. The logic for handling the 'edit_type' and line numbers for code suggestions has been updated. …

Improvements and Error Handling for GitLab Provider

---

CHANGELOG.md
pr_agent/algo/pr_processing.py
pr_agent/algo/utils.py
pr_agent/git_providers/github_provider.py
pr_agent/git_providers/gitlab_provider.py
pr_agent/tools/pr_code_suggestions.py

Refactoring
___
This PR introduces several optimizations to the PR diff processing. It reduces the number of API calls by caching the diff files and only loading them once. It also refactors the load_large_diff function to generate a patch only when necessary, and removes its usage from several places in the code. Additionally, it fixes a major bug in the GitLab provider - The new file was not retrieved correctly
___
-`pr_agent/algo/pr_processing.py`: Removed the usage of `load_large_diff` function in `pr_generate_extended_diff` and `pr_generate_compressed_diff` functions. Also, the `get_pr_diff` function now directly assigns the result of `git_provider.get_diff_files()` to `diff_files` instead of converting it to a list.
-`pr_agent/algo/utils.py`: Refactored the `load_large_diff` …

Optimization of PR Diff Processing

---

CONFIGURATION.md
README.md

Documentation
___
This PR updates the README and CONFIGURATION.md files. It provides more detailed and clear instructions on how to use and configure the PR-Agent tool. It also updates the project's roadmap and adds information about the support for multiple models.
___
-`CONFIGURATION.md`: The changes in this file include more detailed instructions on how to work from CLI, how to edit the configuration of any tool, and how to change a model. It also introduces the concept of 'extra instructions' for all PR-Agent tools.
-`README.md`: This file has been updated to include the support for multiple models in the advantages of PR-Agent. The roadmap has been updated to reflect the support for additional models and the development of additional logic for handling large PRs.

Update README and CONFIGURATION Documentation

---

pr_agent/algo/utils.py
pr_agent/servers/help.py
pr_agent/settings/pr_description_prompts.toml
pr_agent/settings/pr_reviewer_prompts.toml
pr_agent/tools/pr_reviewer.py

Refactoring
___
This PR includes changes that refactor the way YAML is parsed in the codebase. It replaces the 'lstrip' method with 'removeprefix' for more precise string manipulation. Additionally, it updates the format of the prompt descriptions in the settings files to use block scalar format for better readability and consistency.
___
`pr_agent/algo/utils.py`: Replaced the 'lstrip' method with 'removeprefix' for removing the '```yaml' prefix from the review text.
`pr_agent/tools/pr_reviewer.py`: Replaced the 'lstrip' method with 'removeprefix' for removing the '```yaml' prefix from the review text.
`pr_agent/settings/pr_description_prompts.toml`: Updated the format of the prompt descriptions to use block scalar format ('|-') for better readability. …

Block scalar format

---

pr_agent/git_providers/bitbucket_provider.py
pr_agent/tools/pr_code_suggestions.py

I've identified several issues within the `bitbucket_provider.py` file that are affecting the proper functionality of the project. Specifically, the functions `publish_code_suggestions()`, `publish_inline_comment`, and `publish_inline_comments` were missing from the `bitbucket_provider.py` file. To address these issues, I've implemented these functions in the file.
Initially, I encountered challenges due to inadequate documentation regarding these functions. Despite this, I persisted and managed to successfully integrate the missing functionalities. I also encountered difficulties while attempting to create my own function for `inline_comment`. After a considerable amount of effort, I'm pleased to share that the functionality has been restored and improved.
I validated these changes by …

fix bitbucket improve issue

---

INSTALL.md
README.md

Documentation
___
This PR introduces several updates to the `INSTALL.md` and `README.md` files. The installation instructions have been expanded with additional methods and more detailed steps. The readme has been updated with more descriptive text for PR-Agent features, added links to examples, and an updated roadmap. A new feature comparison table has also been added to the readme.
___
`INSTALL.md`: The installation instructions have been expanded with additional methods and more detailed steps. Each method now has its own section with a clear title. The debugging section has been moved to an appendix at the end of the file.
`README.md`: The readme has been updated with more descriptive text for PR-Agent features, added links to examples, and an updated roadmap. A new feature comparison …

Enhancements to Installation Instructions and Readme

---

pr_agent/algo/utils.py
pr_agent/git_providers/azuredevops_provider.py
pr_agent/settings/pr_code_suggestions_prompts.toml
pr_agent/tools/pr_code_suggestions.py

Refactoring
___
This PR refactors the code to use YAML instead of JSON for PR code suggestions. It modifies the `load_yaml` function in `pr_agent/algo/utils.py` to use `yaml.safe_load` instead of `yaml.load`. It also updates the `_prepare_pr_code_suggestions` and `rank_suggestions` methods in `pr_agent/tools/pr_code_suggestions.py` to use `load_yaml` and handle the data as a dictionary. Additionally, it updates the prompts in `pr_agent/settings/pr_code_suggestions_prompts.toml` to reflect the change to YAML.
___
`pr_agent/algo/utils.py`: Updated the `load_yaml` function to use `yaml.safe_load` instead of `yaml.load`.
`pr_agent/tools/pr_code_suggestions.py`: Updated the `_prepare_pr_code_suggestions` and `rank_suggestions` methods to use `load_yaml` and handle the data as a dictionary. …

Refactor Code to Use YAML Instead of JSON for PR Code Suggestions

---

CONFIGURATION.md

Documentation
___
This PR updates the documentation in CONFIGURATION.md to provide more detailed instructions on how to configure the GitHub App. It includes information on the default tools used by the GitHub App, how to override these defaults with a local configuration file, and how to edit specific configuration values for online usage.
___
`CONFIGURATION.md`: The instructions for configuring the GitHub App have been expanded. The document now explains the default tools used by the GitHub App and how to override these with a local configuration file. It also provides more detailed instructions on how to edit specific configuration values for online usage.

Update GitHub App Configuration Instructions

---

CONFIGURATION.md

Documentation
___
This PR updates the documentation in CONFIGURATION.md. It provides instructions on how to edit the prompts for the various PR-Agent tools by overriding the default values in the `.pr_agent.toml` file. It also corrects a minor formatting issue.
___
`CONFIGURATION.md`: The documentation has been updated to include instructions on how to edit the prompts for the PR-Agent tools. This is done by adding the relevant keys to the `.pr_agent.toml` file and overriding the default values. A minor formatting issue was also corrected where the boolean values `true` were previously enclosed in backticks.

Update Configuration Documentation

---

CONFIGURATION.md
README.md
requirements.txt

This PR encompass two critical aspects: documentation improvements and Python requirement specifications about Azure DevOps provider. These enhancements aim to streamline the integration process and ensure seamless functioning of the Azure DevOps provider.

Add docs and dependencies for Azure DevOps provider

---

CONFIGURATION.md
README.md

Documentation
___
This PR includes updates to the CONFIGURATION.md and README.md files. The changes mainly involve rephrasing and reformatting of the existing content, addition of a table of contents in the README, and the removal of certain sections. The purpose of these changes is to improve the clarity and readability of the documentation.
___
`CONFIGURATION.md`: The changes in this file involve minor rephrasing of the content for better clarity. The section on GitHub app specific configurations has been slightly reworded.
`README.md`: Major changes have been made to this file. Certain sections have been commented out, a table of contents has been added, and the 'Overview' section has been updated. The 'Try it now' section has been expanded with more detailed instructions. Some parts …

Update Documentation and README

---

INSTALL.md
README.md
Usage.md

Documentation
___
This PR updates the project's documentation, specifically the README.md and INSTALL.md files. It includes changes to the installation methods' order, updates to the usage guide, and changes in the references to the configuration file. The PR also introduces a new file, Usage.md, which provides a detailed guide on how to use the PR-Agent.
___
`INSTALL.md`: The installation methods' order has been changed. The 'Run from source' method is now the second method, and 'Run as a GitHub Action' is the third. Detailed instructions on how to run from source have been added. References to the configuration file have been updated.
`README.md`: References to the configuration file have been updated throughout the file. The order of the installation methods has been updated to match …

Update Documentation and Reorder Installation Methods

---

pr_agent/git_providers/git_provider.py

- swift was listed twice in the language "if" statement, this PR removes the duplicate line

Removed duplicate swift statement

---

pr_agent/tools/pr_similar_issue.py

Enhancement
___
This PR enhances the logging in the `pr_similar_issue.py` file. It adds logging statements at various stages of the `run` method to provide more visibility into the execution flow. This will help in debugging and understanding the process of fetching similar issues.
___
`pr_agent/tools/pr_similar_issue.py`: Added logging statements in the `run` method to indicate the start and completion of various stages such as getting the issue, querying, and publishing the response.

Enhancing Logging in pr_similar_issue.py

---

README.md
pr_agent/tools/pr_code_suggestions.py
pr_agent/tools/pr_description.py
pr_agent/tools/pr_reviewer.py

Refactoring
___
This PR enhances the error handling in the PR review tools. It wraps the main execution flow of the tools in try-except blocks to catch and log any exceptions that may occur during the review process. This includes the generation of code suggestions, PR descriptions, and PR reviews. The changes aim to make the tools more robust and provide better logging for debugging purposes.
___
`pr_agent/tools/pr_code_suggestions.py`: The main execution flow of the code suggestion generation process is now wrapped in a try-except block. This includes the generation of code suggestions, their ranking, and their publication. Any exceptions that occur during this process are now caught and logged.
`pr_agent/tools/pr_description.py`: The PR description generation process is now wrapped in …

Enhancing error handling in PR review tools

---

INSTALL.md
docs/IMPROVE.md
docs/REVIEW.md

Documentation, Refactoring
___
This PR updates the documentation for the 'improve' and 'review' tools, correcting the titles. It also modifies the execution method for the CLI tool in the INSTALL.md file, changing it from a direct python script execution to a python module execution.
___
`INSTALL.md`: The method of executing the CLI tool has been changed. Instead of directly running the python script, it is now executed as a python module using 'python3 -m'.
`docs/IMPROVE.md`: The title of the document has been corrected from 'Describe Tool' to 'Improve Tool'.
`docs/REVIEW.md`: The title of the document has been corrected from 'Describe Tool' to 'Review Tool'.
</details>

Update Documentation and CLI Execution Method

---

Usage.md

Documentation
___
This PR updates the documentation in the `Usage.md` file. It includes changes to the command line instructions, details on changing a model, and instructions for using Azure and Llama2. The PR also reorganizes some sections for better readability.
___
`Usage.md`: The changes in the `Usage.md` file include:
- Addition of a new section in the Table of Contents titled "Changing a model".
- Modification of the command line instructions to use the module invocation method (`python -m pr_agent.cli`) instead of the script invocation method (`python cli.py`).
- The "Changing a model" section has been moved up and expanded with more details, including instructions on how to use different models and environments not from OPENAI.
- Instructions …

Update and Refactor Documentation

---

README.md
Usage.md
docs/TOOLS_GUIDE.md
pr_agent/settings/pr_reviewer_prompts.toml

Documentation, Enhancement
___
This PR includes updates to the README.md, Usage.md, and docs/TOOLS_GUIDE.md files to improve clarity and provide more detailed instructions. It also modifies the pr_agent/settings/pr_reviewer_prompts.toml file to include an estimate of the effort required to review the PR.
___
`README.md`: The README.md file has been updated to improve the clarity of the instructions. The changes include minor text modifications and the addition of a new feature in the feature list.
`Usage.md`: The Usage.md file has been significantly updated to provide more detailed instructions on how to use the PR-Agent. This includes changes to the introduction, the configuration file section, and the sections on working from a local repo (CLI), …

Update Documentation and Prompts

---

PR_COMPRESSION.md
Usage.md

Documentation
___
This PR updates the documentation to provide more clarity on the PR compression strategy and handling of large PRs. It modifies the 'PR_COMPRESSION.md' and 'Usage.md' files. The changes include renaming 'Git Patch Logic' to 'PR Compression Strategy', reducing the context of each patch from 6 to 3 lines, and adding a section on working with large PRs in the 'Usage.md' file.
___
`PR_COMPRESSION.md`: The title 'Git Patch Logic' has been changed to 'PR Compression Strategy'. The surrounding context of each patch has been reduced from 6 lines to 3 lines. The section 'PR compression strategy' has been renamed to 'Compression strategy'. 
`Usage.md`: A new section 'Working with large PRs' has been added. This section provides information on …

Update Documentation for PR Compression and Large PR Handling

---

Usage.md
pr_agent/algo/pr_processing.py
pr_agent/settings/configuration.toml
pr_agent/settings/pr_add_docs.toml
pr_agent/settings/pr_code_suggestions_prompts.toml
pr_agent/settings/pr_description_prompts.toml
pr_agent/settings/pr_reviewer_prompts.toml
pr_agent/settings/pr_update_changelog_prompts.toml
pr_agent/tools/pr_add_docs.py

Refactoring
___
This PR primarily refactors the handling of patch extra lines in the `pr_processing.py` file. It also updates the prompts in various `.toml` files and adds documentation for the patch extra lines in the `Usage.md` file. The `configuration.toml` file is updated to include a new configuration option for patch extra lines.
___
`pr_agent/algo/pr_processing.py`: Refactored the handling of patch extra lines. The number of extra lines is now configurable and is passed as a parameter to the `pr_generate_extended_diff` function. The `get_pr_diff` function has been updated to get the number of extra lines from the settings.
`pr_agent/tools/pr_add_docs.py`: Updated the call to `get_pr_diff` to reflect the changes in its signature.
`Usage.md`: Added …

Refactoring Patch Extra Lines and Updating Prompts

---

Usage.md
pr_agent/algo/utils.py
pr_agent/git_providers/gitlab_provider.py
pr_agent/tools/pr_code_suggestions.py
pr_agent/tools/pr_reviewer.py

Enhancement
___
This PR introduces several enhancements in the PR-Agent. It modifies the markdown conversion process to support GitHub Flavored Markdown (GFM) and adds the ability to generate links to relevant line numbers in GitLab. It also includes minor changes in the handling of code suggestions and updates the usage documentation.
___
`pr_agent/algo/utils.py`: The `convert_to_markdown` and `parse_code_suggestion` functions have been updated to support GFM. A condition has been added to check if GFM is supported before parsing code suggestions.
`pr_agent/git_providers/gitlab_provider.py`: A new function `generate_link_to_relevant_line_number` has been added to generate links to relevant line numbers in GitLab. The `send_inline_comment` function has …

Enhancements in Markdown Conversion and Line Number Linking

---

README.md

- The update_changelog feature also works with CodeCommit
- This PR updates the README.md file, by adding a checkmark for update_changelog in the CodeCommit column of the features table

added checkmark on features table for update_changelog with CodeCommit

---

pr_agent/git_providers/gitlab_provider.py
pr_agent/tools/pr_code_suggestions.py

publish each suggestion seperatly only on gitlab

---

pr_agent/tools/pr_similar_issue.py

Refactoring, Bug fix
___
This PR introduces several enhancements and error handling mechanisms in the Similar Issue Tool. It includes the addition of time delays after indexing/upserting to ensure Pinecone finalizes its operations before querying. It also includes error handling for parsing issue numbers and a mechanism to skip 'example_issue_' during processing.
___
`pr_agent/tools/pr_similar_issue.py`: The changes in this file include the addition of time delays after indexing and upserting operations to ensure Pinecone finalizes its operations before querying. Error handling has been added for parsing issue numbers, and a mechanism has been introduced to skip 'example_issue_' during processing. Also, a condition has been added to delete an index if …

Enhancements and Error Handling in Similar Issue Tool

---

pr_agent/secret_providers/google_cloud_storage_secret_provider.py
pr_agent/servers/bitbucket_app.py
pr_agent/servers/gitlab_webhook.py

Enhancement
___
This PR enhances the logging in the Bitbucket app, GitLab webhook, and Google Cloud Storage Secret Provider. The changes include:
- Switching to JSON format for logs.
- Adding additional context to the logs.
- Replacing print statements with appropriate logging methods.
___
`pr_agent/secret_providers/google_cloud_storage_secret_provider.py`: Replaced the logger import with a get_logger function. Updated error logging statements to use the new get_logger function.
`pr_agent/servers/bitbucket_app.py`: Replaced print statements with appropriate logging methods. Added additional context to the logs such as server type, sender, API URL, and event type.
`pr_agent/servers/gitlab_webhook.py`: Set up the logger to use JSON format. Added a new …

Enhancing Logging in Bitbucket, GitLab, and Google Cloud Storage Secret Provider

---

INSTALL.md
README.md
Usage.md

Documentation
___
This PR updates the project's documentation and installation instructions. It includes changes to the README.md, INSTALL.md, and Usage.md files. The updates provide clearer instructions, reorganize the content for better readability, and add new sections for additional features and methods of installation and usage.
___
`INSTALL.md`: The installation instructions have been significantly restructured and updated. The methods of installation have been categorized into local, GitHub specific, GitLab specific, and BitBucket specific methods. Each method has been updated with more detailed instructions. New sections have been added for BitBucket specific methods and running on a hosted BitBucket app.
`README.md`: The README file has been …

Update Documentation and Installation Instructions

---

pr_agent/git_providers/github_provider.py
pr_agent/git_providers/utils.py
pr_agent/servers/github_action_runner.py

Refactoring
___
This PR updates the GitHub action to use the '.pr_agent.toml' file from the default branch instead of the head branch. It also includes logging enhancements to provide more information about the application of repository settings. The changes are as follows:
- The '.pr_agent.toml' file is now fetched from the default branch.
- Added logging to indicate the application of repository settings.
- The 'apply_repo_settings' function is now used in the GitHub action runner.
___
`pr_agent/git_providers/github_provider.py`: The '.pr_agent.toml' file is now fetched from the default branch instead of the head branch.
`pr_agent/git_providers/utils.py`: Added logging to indicate the application of repository settings. …

Update GitHub Action to Use .pr_agent.toml

---

docs/GENERATE_CUSTOM_LABELS.md
pr_agent/git_providers/github_provider.py
pr_agent/settings/custom_labels.toml
pr_agent/tools/pr_generate_labels.py
pr_agent/tools/pr_reviewer.py

Refactoring, Documentation
___
This PR includes several changes related to the handling of custom labels and the documentation:
- Refactored the way custom labels are enabled in the settings.
- Updated the exception handling in the `get_repo_settings` method in `github_provider.py`.
- Fixed a typo in the `GENERATE_CUSTOM_LABELS.md` documentation.
- Updated the `custom_labels.toml` file structure.
___
`pr_agent/git_providers/github_provider.py`: Updated the `get_repo_settings` method to remove the reference to the PR head SHA when getting the contents of the `.pr_agent.toml` file. Also, added an exception message when an exception occurs.
`pr_agent/tools/pr_generate_labels.py`: Updated the way `enable_custom_labels` setting is accessed from the settings. …

Refactoring Custom Labels Handling and Documentation Update

---

RELEASE_NOTES.md
Usage.md
docs/GENERATE_CUSTOM_LABELS.md
pr_agent/algo/utils.py
pr_agent/servers/github_action_runner.py

Refactoring, Documentation
___
This PR includes several changes:
- Refactoring of the `github_action_runner.py` script, removing the handling of custom labels.
- Updates to the `RELEASE_NOTES.md` file, detailing the changes and additions in version 0.9.
- Modifications to the `Usage.md` file, improving the instructions for working with GitHub Action.
- Changes to the `GENERATE_CUSTOM_LABELS.md` file, clarifying the usage of custom labels.
___
`pr_agent/servers/github_action_runner.py`: The handling of custom labels has been removed from the script. This includes the removal of the `handle_custom_labels` function and the associated environment variables.
`RELEASE_NOTES.md`: The release notes for version 0.9 have been added, detailing the new features, …

Final Fixes and Updates to PR Agent

---

Usage.md

Documentation
___
This PR updates the 'Usage.md' file to provide more detailed information about the GitHub App features. The changes include:
- Explanation of the new configuration parameters for controlling automatic tool execution based on different PR actions.
- Introduction of the feature to run tools automatically when new code is pushed to an open PR.
- Clarification on how to override default tool parameters using a local configuration file.
___
`Usage.md`: The file has been updated to include more detailed information about the GitHub App features. This includes the introduction of new configuration parameters for controlling automatic tool execution based on different PR actions such as 'opened', 'reopened', 'ready_for_review', and …

Enhance GitHub App features documentation in Usage.md

---

pr_agent/git_providers/gitlab_provider.py
pr_agent/servers/gitlab_webhook.py

Refactoring
___
This PR introduces a logging context to the `handle_request` calls in the `gitlab_webhook.py` file. This enhancement will provide more detailed logging information for debugging and monitoring purposes. The changes are applied to the handling of both 'merge_request' and 'note' events.
___
`pr_agent/servers/gitlab_webhook.py`: The `handle_request` function calls have been updated to include a `log_context` parameter. This change is applied in the handling of 'merge_request' and 'note' events.
</details>

Add Logging Context to Handle Request Calls in gitlab_webhook.py

---

pr_agent/git_providers/bitbucket_provider.py

Refactoring
___
This PR updates the `get_repo_settings` method in `bitbucket_provider.py`. The method now fetches the repository settings file (`.pr_agent.toml`) via an API request instead of using the `get_contents` method from the repository object.
___
`pr_agent/git_providers/bitbucket_provider.py`: The `get_repo_settings` method has been refactored. Instead of using the `get_contents` method from the repository object to fetch the `.pr_agent.toml` file, an API request is now made to fetch the file. The API URL is constructed using the workspace slug, repository slug, and the destination branch. The response from the API request is then encoded to 'utf-8' to get the file contents.
</details>

Update Method to Fetch Repository Settings in bitbucket_provider.py

---

pr_agent/settings/.secrets_template.toml

Bug fix
___
- Fixed a typo in the configuration file for Ollama.
- Updated the comment for the Ollama configuration to provide more accurate information.
___
`pr_agent/settings/.secrets_template.toml`: - Corrected a typo in the Ollama configuration.
- Updated the comment for the Ollama configuration to specify that it's used for local Llama 2, Code Llama, and other models inference endpoint.
</details>

Fix Typo and Update Comment for Ollama Configuration

---

pr_agent/settings/pr_description_prompts.toml
pr_agent/tools/pr_description.py

Bug fix
___
This PR includes two main changes:
- Fixed the loading of AI prediction data in the `pr_description.py` file by properly stripping newline and backtick characters.
- Updated the PR description prompt in `pr_description_prompts.toml` to provide more accurate instructions.
___
`pr_agent/tools/pr_description.py`: Fixed the loading of AI prediction data by stripping newline and backtick characters from the prediction string.
`pr_agent/settings/pr_description_prompts.toml`: Updated the PR description prompt to provide more accurate instructions, emphasizing the importance of focusing on the new PR code and outlining the order of importance for changes.
</details>

Fix PR Description Prompt and Data Preparation

---

pr_agent/algo/file_filter.py
pr_agent/algo/git_patch_processing.py
pr_agent/algo/pr_processing.py
pr_agent/algo/utils.py
pr_agent/git_providers/bitbucket_provider.py
pr_agent/git_providers/git_provider.py
pr_agent/git_providers/github_provider.py
pr_agent/settings/pr_reviewer_prompts.toml

Enhancement
___
This PR introduces several enhancements to the PR processing and patch handling:
- Added handling for different types of file edits (added, deleted, modified, renamed) in both GitHub and Bitbucket providers.
- Enhanced the filtering of ignored files to handle cases where the filename is None.
- Improved the handling of patch deletions to consider the type of edit.
- Modified the PR processing to differentiate between added files and modified files when the token limit is reached.
- Updated the Bitbucket provider to handle cases where updating the PR description fails.
- Minor changes to the logging and error handling.
___
- `pr_agent/algo/file_filter.py`: Updated the filtering of ignored files to handle cases where the filename is None. …

Enhancement of Patch Handling and PR Processing

---

.pr_agent.toml
docs/REVIEW.md
pr_agent/settings/configuration.toml
pr_agent/settings/pr_reviewer_prompts.toml
pr_agent/tools/pr_reviewer.py

Enhancement
___
This PR introduces the following enhancements:
- Adds a new feature to set review labels based on the predicted review effort and security concerns.
- Adds new configuration options to enable or disable these review labels.
- Updates the prompts for effort estimation and security concerns to guide the user to provide the expected format of responses.
___
- `pr_agent/tools/pr_reviewer.py`: Added a new method 'set_review_labels' to set review labels based on the review prediction data. The labels are set for review effort and security concerns if enabled in the settings.
- `.pr_agent.toml`: Added a new configuration option 'enable_review_labels_effort' under 'pr_reviewer' section.
- `pr_agent/settings/configuration.toml`: Added new …

Add Review Labels for Security and Effort Estimation

---

pr_agent/algo/utils.py
pr_agent/settings/pr_code_suggestions_prompts.toml
pr_agent/tools/pr_reviewer.py
tests/unittest/test_load_yaml.py

Refactoring
___
This PR focuses on improving the handling and parsing of YAML data in the application. The main changes include:
- Refactoring the `load_yaml` and `try_fix_yaml` functions in `pr_agent/algo/utils.py` to improve error handling and make the code more robust.
- The `load_yaml` function now takes a `response_text` parameter instead of `review_text`.
- The `try_fix_yaml` function now checks for more keys ('relevant line:', 'suggestion content:', 'relevant file:') to fix the YAML.
- In `pr_agent/tools/pr_reviewer.py`, the `load_yaml` function is now used to parse the prediction data.
- The unit tests in `tests/unittest/test_load_yaml.py` have been updated to reflect these changes.
- The prompts in `pr_agent/settings/pr_code_suggestions_prompts.toml` have been updated for better …

Enhancements in YAML Parsing and Error Handling

---

Usage.md
pr_agent/algo/file_filter.py
pr_agent/algo/utils.py

Enhancement
___
This PR introduces several improvements:
- Enhances the handling of glob patterns in the file filtering process. It now supports both string and list formats for the glob setting.
- Changes the logging level from error to debug when failing to parse YAML for config override in utils.py.
- Updates the Usage.md documentation to reflect the changes in glob pattern handling.
___
- `pr_agent/algo/file_filter.py`: Improved the handling of glob patterns. The code now checks if the patterns are in string format, and if so, converts them to a list. It also supports multiple glob patterns separated by commas.
- `pr_agent/algo/utils.py`: Changed the logging level from error to debug for the case when YAML parsing for config override fails.
- …

Enhance glob pattern handling and logging in file filtering

---

pr_agent/servers/github_action_runner.py

A utility function (`is_true`) was added to take care of validating and converting boolean values from string or boolean types. This function is used in three parts of the `run_action` method where automatic PR review, description, and improvement actions are triggered based on environment settings. This change makes the condition checks cleaner and prevents code duplication.

Add utility function to handle boolean type conversion

---

pr_agent/servers/github_action_runner.py

A new function `get_setting_or_env` was implemented to facilitate fetching of either settings or environmental variables in the GitHub Action Runner. This was necessary to resolve an issue where a certain undefined behaviour occurs in GitHub Actions, leading to an attribute error. The new function also provides a default value parameter to ensure the return of a value even in failed attempts to fetch from either settings or environment variables.

"Add fallback to environment variables in GitHub Action Runner"

---

docs/REVIEW.md

Description:
This pull request addresses an issue where the current image in pr-agent/docs/Review.md was referencing the wrong prompt result. The initial image incorrectly reflected the output of a '/describe' prompt, while it should have represented the '/review' prompt. The updated image now accurately corresponds to the desired prompt result, resolving the inconsistency.
Changes:
- Updated pr-agent/docs/Review.md image to correct prompt reference.
- Ensured alignment with '/review' prompt output.

Update pr-agent/docs/Review.md Image

---

Usage.md

documentation
___
This PR updates the Usage.md file with a new section on how to work with BitBucket Self-Hosted App. It provides instructions on how to customize configuration parameters by uploading a local `.pr_agent.toml` file to the root of the repo's main branch. An example of such customization is also included.
___
- `Usage.md`: Added a new section "Working with BitBucket Self-Hosted App" with instructions on how to customize configuration parameters using a local `.pr_agent.toml` file. The Table of Contents was also updated to include this new section.
</details>

Update Usage.md with BitBucket Self-Hosted App section

---

docs/docs/tools/improve.md
pr_agent/settings/configuration.toml

A small refinement to the documentation.

doc: title refinement
