- pr_agent/algo/token_handler.py
Force special tokens to be encoded as natural text when using `tiktoken`
> Fix encoding error on special_tokens

- pr_agent/algo/git_patch_processing.py
- pr_agent/git_providers/git_provider.py
- pr_agent/git_providers/github_provider.py
- pr_agent/git_providers/gitlab_provider.py
- pr_agent/tools/pr_reviewer.py
example output in Gitlab:
https://gitlab.com/hussam.l/pr_agent/-/merge_requests/3//diffs
> Inline suggestion refactor + supporting GitLab 

- pr_agent/algo/git_patch_processing.py
- pr_agent/algo/pr_processing.py
- pr_agent/cli.py
- pr_agent/config_loader.py
- pr_agent/git_providers/git_provider.py
- pr_agent/git_providers/github_provider.py
- pr_agent/git_providers/gitlab_provider.py
- pr_agent/settings/configuration.toml
- pr_agent/settings/pr_code_suggestions_prompts.toml
- pr_agent/tools/pr_code_suggestions.py
- pr_agent/tools/pr_description.py
Type of PR:
___
**This PR introduces a new feature that allows the conversion of hunks in a patch to numbered hunks, and the generation of code suggestions for a PR. It also includes the necessary changes to support this feature in the Github and Gitlab providers, and updates the CLI and configuration settings accordingly.**
___
-`pr_agent/algo/git_patch_processing.py`: Added a new function `convert_to_hunks_with_lines_numbers` that converts a patch to numbered hunks. This function is used to generate more detailed diffs for code suggestions.
-`pr_agent/algo/pr_processing.py`: Updated the `get_pr_diff` function to support the addition of line numbers to hunks. This is used when generating the PR diff for code suggestions. …
> Adding numbered hunks and code suggestions feature

- pr_agent/settings/pr_code_suggestions_prompts.toml
- pr_agent/settings/pr_reviewer_prompts.toml
Type of PR:
**Bug fix**
___
**This PR addresses minor typographical errors in the prompts of two settings files. The changes are aimed at improving the clarity and correctness of the instructions provided in the prompts.**
___
- `pr_agent/settings/pr_code_suggestions_prompts.toml`: A repeated word 'provide' was removed from the prompt instructions.
- `pr_agent/settings/pr_reviewer_prompts.toml`: A repeated word 'provide' was removed from the prompt instructions.
> Minor Typos Fix in Prompt Files

- pr_agent/git_providers/__init__.py
- pr_agent/git_providers/bitbucket_provider.py
- pr_agent/settings/.secrets_template.toml
In a world where not all developers use GitHub, this pull request adds a handler to review Pull Requests from Bitbucket as well in order to bridge the gap between platforms and ensuring no PR goes unnoticed.
Let's unite the coding universe!
-----
Type of PR:
___
**This PR introduces support for Bitbucket as a git provider. It includes the implementation of a new BitbucketProvider class, which handles interactions with the Bitbucket API, and the addition of Bitbucket to the list of supported git providers.**
___
- `pr_agent/git_providers/__init__.py`: BitbucketProvider is imported and added to the _GIT_PROVIDERS dictionary.
- `pr_agent/git_providers/bitbucket_provider.py`: This is a new file that implements the BitbucketProvider …
> Adding Bitbucket Provider Support

- pr_agent/git_providers/bitbucket_provider.py
- pr_agent/git_providers/github_provider.py
- pr_agent/git_providers/gitlab_provider.py
- pr_agent/tools/pr_description.py
- pr_agent/tools/pr_questions.py
Type of PR:
___
**This PR removes the 'get_description' function from the Bitbucket, GitHub, and GitLab providers. Instead, it uses the 'get_pr_description' function in the 'pr_description.py' and 'pr_questions.py' files. This change aims to reduce code duplication and improve maintainability.**
___
-`bitbucket_provider.py`: Removed the 'get_description' function.
-`github_provider.py`: Removed the 'get_description' function.
-`gitlab_provider.py`: Removed the 'get_description' function.
-`pr_description.py`: Replaced the 'get_description' function call with 'get_pr_description'.
-`pr_questions.py`: Replaced the 'get_description' function call with 'get_pr_description'.
> Removal of Duplicate Function Across Git Providers

- pr_agent/agent/pr_agent.py
- pr_agent/algo/pr_processing.py
- pr_agent/algo/utils.py
- pr_agent/cli.py
- pr_agent/git_providers/bitbucket_provider.py
- pr_agent/git_providers/git_provider.py
- pr_agent/git_providers/github_provider.py
- pr_agent/git_providers/gitlab_provider.py
- pr_agent/tools/pr_questions.py
- pr_agent/tools/pr_reviewer.py
Use `/review -i` to review only new commits that hasn't been reviewed since the last pr-agent review, instead of full review to the entire PR (from the first commit).
How is works:
The pr-agent will search last review published by the PR-Agent and review all the subsequent commits that hasn't been reviewed yet ( `* commits where commit_date > last_review_date`)
> Add Incremental Review /review -i

- CONFIGURATION.md
- pr_agent/algo/utils.py
- pr_agent/settings/configuration.toml
- pr_agent/settings/pr_reviewer_prompts.toml
- pr_agent/tools/pr_reviewer.py
Type of PR:
___
**This PR introduces a new feature to the PR Reviewer tool, allowing it to calculate a score for each PR. The score is a float value between 0 and 100, representing the quality of the PR. The PR also includes updates to the configuration files to enable or disable this feature.**
___
-`pr_agent/algo/utils.py`: Added a new emoji for the score in the markdown conversion function.
-`pr_agent/tools/pr_reviewer.py`: Added a new variable 'require_score' to the PR Reviewer's variables, which is fetched from the settings.
-`CONFIGURATION.md`: Updated the documentation to include the new 'require_score_review' flag.
-`pr_agent/settings/configuration.toml`: Added a new flag 'require_score_review' to enable or disable the …
> Add Score Review Feature

- pr_agent/git_providers/github_provider.py
- pr_agent/settings/configuration.toml
PR Type:
___
**This PR introduces a new configuration option to control the publishing of progress comments in the PR. This option can be toggled on or off in the configuration file. Additionally, the PR includes some minor refactoring in the comment handling logic.**
___
-`pr_agent/git_providers/github_provider.py`: Added a check for the new `publish_output_progress` setting before publishing a temporary comment. Also, modified the `remove_initial_comment` method to use `getattr` for safer attribute access.
-`pr_agent/settings/configuration.toml`: Added a new configuration option `publish_output_progress` to control whether progress comments should be published or not.
> Add Option to Control Comment Publishing Progress

- pr_agent/git_providers/gitlab_provider.py
Fixes:
```
Traceback (most recent call last):
File "/Users/sambolgert/Documents/workspace/pr-agent/pr_agent/cli.py", line 75, in <module>
run()
File "/Users/sambolgert/Documents/workspace/pr-agent/pr_agent/cli.py", line 55, in run
reviewer = PRCodeSuggestions(args.pr_url)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/sambolgert/Documents/workspace/pr-agent/pr_agent/tools/pr_code_suggestions.py", line 20, in __init__
self.git_provider = get_git_provider()(pr_url)
^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class GitLabProvider with abstract method publish_inline_comments
```
> Fix TypeError for GitlabProvider

- pr_agent/algo/pr_processing.py
- pr_agent/algo/token_handler.py
- pr_agent/settings/configuration.toml
- pr_agent/tools/pr_code_suggestions.py
- pr_agent/tools/pr_description.py
- pr_agent/tools/pr_information_from_user.py
- pr_agent/tools/pr_questions.py
- pr_agent/tools/pr_reviewer.py
PR Type:
___
**This PR introduces the ability to use fallback models for tokenization in the event that the primary model fails. It modifies the get_pr_diff and pr_generate_compressed_diff functions to accept a model parameter, and uses this parameter to determine the token limit. It also introduces a new function, retry_with_fallback_models, which attempts to generate a prediction with each model in a list until successful. The PR also updates various other functions and files to accommodate these changes.**
___
-`pr_agent/algo/pr_processing.py`: Modified get_pr_diff and pr_generate_compressed_diff to accept a model parameter, and added retry_with_fallback_models function.
-`pr_agent/algo/token_handler.py`: Removed the limit …
> Implementing Fallback Models for Tokenization

- pr_agent/git_providers/gitlab_provider.py
PR Type:
**Bug fix**
___
**This PR addresses an issue with the GitLab Provider where it was not correctly handling pagination for merge request diffs. The fix ensures that all diffs are retrieved by passing the 'get_all=True' argument to the 'list' method.**
___
-`git_providers/gitlab_provider.py`: The change is made in the '_set_merge_request' method where the 'get_all=True' argument is added to the 'list' method call on 'self.mr.diffs'. This ensures that all diffs are retrieved, not just the ones on the current page.
> Fix for GitLab Paginator in GitLab Provider

- pr_agent/agent/pr_agent.py
- pr_agent/cli.py
- pr_agent/servers/help.py
- pr_agent/tools/pr_description.py
Just thought these might be useful:
1. Added option to used the describe command with -c instead of setting the configuration `publish_description_as_comment`. Can be useful when you just want to see what the PR-Agent says but you don't want it to edit your description (maybe you already have a very detailed one but you just want to get a second opinion)
2. The markdown styling of describe as comment vs describe as PR description was a little different. I changed the styling of the PR description to match the one of the comment because I think having an entire paragraph in **bold** is messier than the clean header+paragraph style of the description as comment.
> Minor improvements to describe command

- CHANGELOG.md
- pr_agent/settings/pr_code_suggestions_prompts.toml
- pr_agent/settings/pr_information_from_user_prompts.toml
- pr_agent/settings/pr_questions_prompts.toml
- pr_agent/settings/pr_reviewer_prompts.toml
- pr_agent/settings/pr_update_changelog_prompts.toml
- pr_agent/tools/pr_code_suggestions.py
- pr_agent/tools/pr_description.py
- pr_agent/tools/pr_information_from_user.py
- pr_agent/tools/pr_questions.py
- pr_agent/tools/pr_reviewer.py
- pr_agent/tools/pr_update_changelog.py
Enhancement
___
This PR updates several tools in the `pr_agent` package to use the commit messages in their functionality. The commit messages are now retrieved and stored in the `vars` dictionary for each tool.
___
- `pr_agent/tools/pr_code_suggestions.py`: Added the `commit_messages_str` key to the `vars` dictionary.
- `pr_agent/tools/pr_description.py`: Removed the `commit_messages_str` variable and added the `commit_messages_str` key to the `vars` dictionary.
- `pr_agent/tools/pr_information_from_user.py`: Added the `commit_messages_str` key to the `vars` dictionary.
- `pr_agent/tools/pr_questions.py`: Added the `commit_messages_str` key to the `vars` dictionary.
- `pr_agent/tools/pr_reviewer.py`: Added the `commit_messages_str` key to the `vars` dictionary.
- …
> Use commit messages in PR tools

- pr_agent/algo/git_patch_processing.py
Bug fix
___
This PR addresses an edge case in the git patch processing algorithm. The edge case occurs when the patch string is '@@ -0,0 +1 @@', which previously caused an error. The PR adds exception handling to prevent this error.
___
- `pr_agent/algo/git_patch_processing.py`: Added exception handling in two places where the patch string is parsed. If the parsing fails due to the edge case, it now defaults to a specific value.
> Handling edge case for hunks in git patch processing

- README.md
- pr_agent/cli.py
- requirements.txt
Bug fix
___
This PR corrects the command line interface (CLI) and README descriptions for the `pr_url` parameter, changing it from `--pr-url` to `--pr_url`. Additionally, it removes a duplicate entry in the requirements.txt file.
___
`pr_agent/cli.py`: Updated the usage and help descriptions for the `pr_url` parameter in the CLI.
`README.md`: Updated the examples for invoking the different tools via the CLI, correcting the `pr_url` parameter.
`requirements.txt`: Removed a duplicate entry.
> Correcting CLI and README Descriptions and Fixing Requirements.txt

- INSTALL.md
The `Contents` permission is missing from the install doc for creating a GitHub App but this permission is needed to read commits for use with `/review -i`.
> Contents read-only permission needed by /review -i

- pr_agent/tools/pr_code_suggestions.py
When `/improve` does not return any suggestions, currently it is unclear if the request failed or there were no suggestions.
This change adds a comment on the PR when no suggestions are returned. 
I don't feel strongly about the specific wording of the comment, but I think it is helpful to post something when there are no suggestions.
> Publish comment when improve has no suggestions

- INSTALL.md
- pr_agent/git_providers/bitbucket_provider.py
- pr_agent/git_providers/git_provider.py
- tests/unittest/test_bitbucket_provider.py
This PR fixes an error in the BitbucketProvider class.
I was testing out the pr-agent for Bitbucket (the CLI version) and I got the following error:
> `AttributeError: 'BitbucketProvider' object has no attribute 'get_repo_settings'`
This PR fixes that error, and after this code was in place, the pr-agent was able to successfully comment on my Bitbucket PR.
Other modifications:
- added get_repo_settings() as an abstract method in the parent GitProvider class, since it is used in the GitHub and GitLab classes also.
- added a unit test for the BitbucketProvider URL parser.
- added a `chmod` command on the `.secrets.toml` in the `INSTALL.md` instructions.
(Note: Ignore PR 204 and PR 205)
> Implement get_repo_settings for BitbucketProvider

- pr_agent/agent/pr_agent.py
- pr_agent/servers/github_app.py
- pr_agent/settings/configuration.toml
- pr_agent/tools/pr_reviewer.py
Enhancement
___
This pull request introduces an automatic review feature for the GitHub app. The `auto_review` command is added for an "opened" or "created" action for a pull request. This command triggers the PRReviewer to automatically review the pull request. The automatic review feature can be enabled or disabled through the settings. Additional logging has been added to provide more context when processing requests.
___
`pr_agent/agent/pr_agent.py`: Added the "auto_review" command to the command2class dictionary. This command triggers the PRReviewer. Also, added more logging to provide additional context when processing requests.
`pr_agent/servers/github_app.py`: Changed the command from "/review" to "/auto_review" in the handle_request function. This change triggers the automatic …
> Addition of Automatic Review Configuration for GitHub App

- pr_agent/algo/utils.py
I noticed this bug when trying to run some command with `--config.verbosity_level=3` and got this error:
```log
File "/home/vcap/app/pr_agent/agent/pr_agent.py", line 81, in handle_request
await command2class[action](pr_url, args=args).run()
File "/home/vcap/app/pr_agent/tools/pr_code_suggestions.py", line 50, in run
await retry_with_fallback_models(self._prepare_prediction)
File "/home/vcap/app/pr_agent/algo/pr_processing.py", line 217, in retry_with_fallback_models
return await f(model)
File "/home/vcap/app/pr_agent/tools/pr_code_suggestions.py", line 68, in _prepare_prediction
self.prediction = await self._get_prediction(model)
File "/home/vcap/app/pr_agent/tools/pr_code_suggestions.py", line 76, in _get_prediction
if get_settings().config.verbosity_level >= 2:
TypeError: '>=' not …
```
> Safe parse key value in config override

- INSTALL.md
Documentation
___
This PR updates the installation guide with instructions on how to use a specific version of the Docker image by referencing its digest. It also provides guidance on how to pin a GitHub Action to a specific commit for stability reasons. These additions aim to enhance reproducibility and stability in the usage of the tool.
___
`INSTALL.md`: The changes in the INSTALL.md file include the addition of instructions on how to use a specific version of the Docker image by referencing its digest. It also includes an example of how to run a review and ask a question using a specific digest. Furthermore, it provides an example of how to pin a GitHub Action to a specific commit.
> Adding Instructions for Specific Docker Image Version and GitHub Action Commit in Installation Guide

- pr_agent/git_providers/gitlab_provider.py
- pr_agent/settings/configuration.toml
Bug fix
___
This PR addresses an issue where GitLab was unable to display the diff on the page due to incorrect SHA's, resulting in 400 or 500 errors. The fix involves finding the correct diff for the change to ensure accurate SHA's. If no valid diff is found, the system will fall back to the last diff as per the original code. A new exception class 'DiffNotFoundError' has been introduced to handle scenarios where no diffs are found in the merge request.
___
`pr_agent/git_providers/gitlab_provider.py`: Introduced a new method 'get_relevant_diff()' to find the correct diff for a given file and line. This method is now used in 'send_inline_comment()' to ensure the correct diff is used when sending inline comments. A new exception 'DiffNotFoundError' has been introduced and is raised when no …
> Fixing GitLab Inline Comment Diff Issue by Implementing Relevant Diff Selection

- pr_agent/git_providers/bitbucket_provider.py
* I believe that @sarbjitsinghgrewal and I submitted PRs to fix a missing get_repo_settings() function in bitbucket_provider, at the same time. We added the function to different parts of the file, so that is how the git merge (and us humans) missed the duplicate.
* In this PR, I am removing my copy that I added in commit f82b962
> Remove duplicate get_repo_settings() in bitbucket_provider

- INSTALL.md
Could we consider adding permissions to the GitHub Actions section?
I've noticed that this has been a point of confusion for some users, as evidenced by questions in our Discord channel and GitHub issues. Some folks may even be discouraged to the point of not seeking help. I believe adding permissions could significantly improve the user experience. What are your thoughts?
> adding permissions to the GitHub Actions section of INSTALL

- requirements.txt
will add additional testing if the initial version bump pr looks good. 
We're also adding testing on our end to debugging is opt-in only. https://github.com/BerriAI/litellm/blob/main/litellm/tests/test_litedebugger_integration.py
> bump litellm version - prevent default logging

- README.md
- pr_agent/git_providers/codecommit_client.py
- pr_agent/git_providers/codecommit_provider.py
- tests/unittest/test_codecommit_client.py
Enhancement
___
This PR implements the 'improve' command for CodeCommit.
- Implements the 'publish_code_suggestions()' function, which is used by the 'improve' command, by adding the ability to annotate comments by file and line number
- Note that AWS CodeCommit is not as feature-rich as the GitHub site. for example, you cannot highlight a range of line numbers in a file... you can only specify the starting line number for a comment
- Improves error handling when talking to AWS API by adding more specific error messages
___
`pr_agent/git_providers/codecommit_client.py`: Added more specific error messages for various exceptions. Added the ability to annotate comments with file and line information. Also, added the 'repo_name' parameter to the 'get_pr' method to provide a more specific …
> implement 'improve' command for CodeCommit

- pr_agent/git_providers/gerrit_provider.py
+ removed markdown/html formatting from the review due to gerrit does not support it
> [gerrit] Added support project's config file: `.pr_agent.toml`

- Usage.md
- pr_agent/settings/.secrets_template.toml
Hi, 
Just a small doc update showing how to call local huggingface models using Ollama / VLLM 
Key Change: 
**Local**  
You can run Huggingface models locally through either [VLLM](https://docs.litellm.ai/docs/providers/vllm) or [Ollama](https://docs.litellm.ai/docs/providers/ollama)
E.g. to use a new Huggingface model locally via Ollama, set:
```
[__init__.py]
MAX_TOKENS = {
"model-name-on-ollama": <max_tokens>
}
e.g.
MAX_TOKENS={
...,
"llama2": 4096
}
[config] # in configuration.toml
model = "ollama/llama2"
[ollama] # in .secrets.toml
api_base = ... # the base url for your huggingface inference endpoint 
```
> adding documentation on how to call local hf models

- pr_agent/algo/git_patch_processing.py
Bug fix
___
This PR addresses potential issues in the git patch processing code where match groups could be null. The changes ensure that any null values are replaced with 0 to prevent errors during the mapping to integers.
___
`pr_agent/algo/git_patch_processing.py`: Added null checks for match group values in the extend_patch and convert_to_hunks_with_lines_numbers functions. If any value is null, it is replaced with 0 before mapping to integers.
> Fixing potential null values in git patch processing

- pr_agent/git_providers/git_provider.py
- pr_agent/git_providers/github_provider.py
- pr_agent/git_providers/gitlab_provider.py
- pr_agent/tools/pr_description.py
Enhancement
___
This PR introduces a new method, `get_pr_id`, in the abstract Git Provider class and its implementations (GitHub and GitLab). The method is designed to return the PR ID, which is used in the PR Description tool. This change provides a more consistent and error-tolerant way of fetching the PR ID across different Git providers.
___
`pr_agent/git_providers/git_provider.py`: Added the abstract method `get_pr_id` to the abstract Git Provider class.
`pr_agent/git_providers/github_provider.py`: Implemented the `get_pr_id` method for the GitHub provider, which returns the PR ID in the format "repo/pr_num".
`pr_agent/git_providers/gitlab_provider.py`: Implemented the `get_pr_id` method for the GitLab provider, which returns the PR ID as the web …
> Adding get_pr_id method to Git Providers

- pr_agent/settings/pr_code_suggestions_prompts.toml
- pr_agent/settings/pr_reviewer_prompts.toml
Documentation
___
This PR updates the review guidelines in two configuration files. The changes specify that reviewers should not suggest adding docstrings, type hints, or comments to the code. This update is reflected in both 'pr_code_suggestions_prompts.toml' and 'pr_reviewer_prompts.toml' files.
___
`pr_agent/settings/pr_code_suggestions_prompts.toml`: The instructions for code suggestions have been updated to include 'comments' in the list of items that should not be suggested for addition.
`pr_agent/settings/pr_reviewer_prompts.toml`: The review guidelines have been updated to specify that reviewers should not suggest adding docstrings, type hints, or comments.
</details>
> Update Review Guidelines to Exclude Comments

- pr_agent/settings/language_extensions.toml
[Bun](https://github.com/oven-sh/bun) uses `bun.lockb` binary files which cause pr-agent to crash with `UnicodeDecodeError`  when encountered.
E.g:
```
INFO:root:Getting PR diff...
WARNING:root:Cannot decode file bun.lockb or bun.lockb in merge request 1
WARNING:root:Failed to generate prediction with gpt-4: Traceback (most recent call last):
File "/app/pr_agent/algo/pr_processing.py", line 215, in retry_with_fallback_models
return await f(model)
File "/app/pr_agent/tools/pr_reviewer.py", line 131, in _prepare_prediction
self.patches_diff = get_pr_diff(self.git_provider, self.token_handler, model)
File "/app/pr_agent/algo/pr_processing.py", line 60, in get_pr_diff
patches_extended, total_tokens, patches_extended_tokens = pr_generate_extended_diff(pr_languages, token_handler,
File …
```
> Add lockb to bad extensions

- pr_agent/git_providers/azuredevops_provider.py
There are scenarios when file is not available at specific commit. When this happens, file content should be treated as empty and continue processing next file
Example
`TF401174: The item \'fileA.js\' could not be found in the repository \'X\' at the version specified by \'<Commit: XXXXX >\' (resolved to commit \'XXXXX\')`
> Azure Devops: Set file content as empty string when azure_devops_client.get_item fails

- INSTALL.md
- Usage.md
- pr_agent/algo/file_filter.py
- pr_agent/algo/pr_processing.py
- pr_agent/config_loader.py
- pr_agent/settings/ignore.toml
- tests/unittest/test_file_filter.py
This PR adds support for ignoring files by introducing an `ignore.toml` configuration file and a `file_filter.py` module.
Also:
- Updates relevant code to use the file filter.
- Unit tests
- Usage doc updates + plenty of code comments 
- Fixup minor doc nits
This code has also been tested locally against some of my own PRs.
Closes #351
> Add support for ignoring files

- pr_agent/tools/pr_reviewer.py
This changes the help message to display properly when running a custom deployment of the PR-Agent app (i.e. not via GitHub Actions, and with the setting `github_app.override_deployment_type=false`)
> Fixed help message for bot user

- pr_agent/git_providers/azuredevops_provider.py
This update removes the restriction of having 'azure.com' in the Azure DevOps URL, allowing for custom domain URLs. This enhancement caters to organizations with unique domain setups, ensuring broader usability and flexibility in Azure DevOps integration.
> Support Custom Domain URLs for Azure DevOps Integration

- pr_agent/git_providers/github_provider.py
When getting the last commit in `/review -i` consider also the last __incremental__ review, not just the last __full__ review
Full disclosure I'm not really sure the `/review -i` feature work very well - I might be wrong but it seemed like the actual review in fact addressed all the changes in the PR, and not just the ones from the last review (even though it adds a link to the commit of the last review).   I think the commit list gathered in `/review -i` doesn't propagate to the actual list the reviewer uses. Again, I might be wrong, just took a brief glance at it.
> Get previous incremental review

- docs/IMPROVE.md
- docs/REVIEW.md
- pr_agent/settings/configuration.toml
- pr_agent/settings/pr_description_prompts.toml
- pr_agent/settings/pr_reviewer_prompts.toml
- pr_agent/tools/pr_description.py
Documentation, Enhancement
___
This PR includes updates to the documentation and configuration settings for PR descriptions. The main changes are:
- Added a new configuration option to use bullet points in PR descriptions.
- Updated the documentation files (IMPROVE.md and REVIEW.md) to include a note on code suggestions quality.
- Updated the prompts configuration files to reflect the new changes.
___
`pr_agent/tools/pr_description.py`: Added a new configuration option 'use_bullet_points' to the PR description settings.
`docs/IMPROVE.md`: Added a new section on code suggestions quality, providing guidance on how to use and interpret the suggestions.
`docs/REVIEW.md`: Added a new section on code suggestions quality, providing guidance on how to use and …
> Enhancing Documentation and Updating Configuration for PR Descriptions

- pr_agent/settings/language_extensions.toml
- pr_agent/tools/pr_add_docs.py
Enhancement
___
- This PR addresses the issue of adding documentation to non-editable file extensions like SQL, YAML, etc.
- A blacklist of such file extensions has been added to prevent the addition of inline documentation to these files.
- The changes are mainly in the 'pr_agent/tools/pr_add_docs.py' and 'pr_agent/settings/language_extensions.toml' files.
___
`pr_agent/tools/pr_add_docs.py`: Added a check to disable adding docs to scripts and other non-relevant text files. The blacklist of extensions is fetched from the settings.
`pr_agent/settings/language_extensions.toml`: Added a new section 'docs_blacklist_extensions' to list the file extensions for which documentation should not be added.
</details>
> Add Blacklist for Non-Editable File Extensions in Documentation

- pr_agent/git_providers/bitbucket_provider.py
- pr_agent/git_providers/codecommit_provider.py
- pr_agent/git_providers/gerrit_provider.py
- pr_agent/git_providers/git_provider.py
- pr_agent/git_providers/github_provider.py
- pr_agent/git_providers/gitlab_provider.py
- pr_agent/git_providers/local_git_provider.py
- pr_agent/servers/github_app.py
- pr_agent/servers/utils.py
- pr_agent/settings/configuration.toml
- pr_agent/tools/pr_reviewer.py
The new feature can be enabled via the new configuration `github_app.handle_push_trigger`. To avoid any unwanted side-effects, the current default of this configuration is set to `false`.
The high level flow (assuming the configuration is enabled):
1. new code is pushed to the repo
2. receive pull_request.synchronize event from GitHub
3. extract PR url from request body
4. validate trigger is valid to run the agent (PR is open, no duplicate triggers, etc.)
5. perform configured commands (e.g. `/describe`, `/review -i`)
The push trigger flow is guarded by a backlog queue so that multiple events for the same PR won't trigger multiple duplicate runs of the PR-Agent commands. Example timeline:
1. push 1 - start handling event
2. push 2 - waiting to be handled while push 1 event is still …
> Added support for automatic review on push event

- pr_agent/tools/pr_reviewer.py
Hey @mrT23, I think there's a problem with moving this line to after `self.git_provider.publish_comment(pr_comment)`.
The reason I originally placed it here is because otherwise, if you run `/review --pr_reviewer.remove_previous_review_comment=true` it will publish your review and then immediately after delete it, because it will look for the previous review comment only after you published your new review - so it will take your new review as the previous one. In order to get the real "previous" review you must collect the comments list before publishing a review, so placing this method call first ensures that.
The method `self._get_previous_review_comment()` is a no-op if `pr_reviewer.remove_previous_review_comment=false` so I see no downside in keeping it before …
> Fix call to `_get_previous_review_comment`

- pr_agent/tools/pr_reviewer.py
If the last commit message is this:  
Fix in _some_func
Then before this fix it would appear this way in the incremental PR review:  
_(Fix in _some_func)_
But after this fix it would appear correctly this way:  
_(Fix in \_some\_func)_
> Fix formatting when last commit message contains _

- pr_agent/tools/pr_reviewer.py
Bug fix
___
This PR fixes a syntax error in an f-string expression in the `pr_reviewer.py` file. The error was caused by the inclusion of a backslash in the expression part of the f-string. The fix involves replacing the backslash with a suitable replacement.
___
`pr_agent/tools/pr_reviewer.py`: The f-string expression that was causing a SyntaxError has been fixed. The backslash in the expression part of the f-string has been replaced with a suitable replacement. The modified f-string is used to append a commit message to the `incremental_review_markdown_text` string.
</details>
> Fix Syntax Error in f-string Expression

- pr_agent/git_providers/git_provider.py
This can happen for example when you have one commit add a line to a file and the next commit deletes that line. Then if those are the only 2 commits in the PR the diff will be empty.
> Fix error in `get_main_pr_languages` when the diff is empty

- pr_agent/servers/github_app.py
Refactoring
___
This PR refactors the command handling in the GitHub app server. The changes allow different command configurations to be used depending on the trigger event. Specifically:
- The `_perform_commands` function now takes an additional parameter `commands_conf` to specify the command configuration to use.
- For 'review_requested' events, the 'pr_commands' configuration is used.
- For 'synchronize' events, the 'push_commands' configuration is used.
___
`pr_agent/servers/github_app.py`: The `_perform_commands` function has been modified to take an additional parameter `commands_conf`, which is used to determine the command configuration to use. This parameter is passed in from the `handle_request` function, which uses 'pr_commands' for …
> Refactor Command Handling for Different Triggers

- pr_agent/servers/serverless.py
Bug fix
___
This PR addresses a bug where middleware was not being added during the initialization of FastAPI in a lambda function. The following changes have been made:
- Middleware has been imported from starlette.
- Middleware has been added to the FastAPI app during initialization.
___
`pr_agent/servers/serverless.py`: Middleware has been imported from starlette and added to the FastAPI app during its initialization. This change ensures that the middleware is correctly set up when the FastAPI app is created.
</details>
___
In a function for a Lambda function, middleware was not added during the initialization of FastAPI, and it was causing a [ContextDoesNotExistError](https://starlette-context.readthedocs.io/en/latest/errors.html), so I added the …
> Adding Middleware to FastAPI Initialization

- docs/REVIEW.md
- pr_agent/git_providers/git_provider.py
- pr_agent/git_providers/github_provider.py
- pr_agent/settings/configuration.toml
- pr_agent/tools/pr_reviewer.py
Enhancement
___
This PR introduces new configurations to manage the frequency of automatic incremental reviews triggered by a push event. The main changes include:
- Added properties `first_new_commit_sha` and `last_seen_commit_sha` in the `IncrementalPR` class in `git_provider.py`.
- Modified `get_commit_range` method in `github_provider.py` to assign commit objects instead of commit SHA to `first_new_commit` and `last_seen_commit`.
- Updated `run` method in `pr_reviewer.py` to check for the number of new commits and their recency before starting the review.
- Added new configurations in `configuration.toml` to specify the minimum number of commits and minimum time elapsed for an incremental review.
___
`pr_agent/git_providers/git_provider.py`: …
> Implementing Thresholds for Incremental PR Reviews

- pr_agent/settings/configuration.toml
- pr_agent/settings/pr_custom_labels.toml
- pr_agent/settings/pr_description_prompts.toml
- pr_agent/settings/pr_reviewer_prompts.toml
- pr_agent/tools/pr_description.py
- pr_agent/tools/pr_reviewer.py
Refactoring
___
This PR introduces several changes related to PR labels handling and display:
- The 'PR Labels' key is now used instead of 'PR Type' to prepare labels.
- The 'PR Labels' key is not displayed in the markdown text.
- A new configuration option 'enable_pr_type' is added to control whether to display 'PR Type' in the markdown text.
- The 'set_custom_labels' function call is commented out in 'pr_reviewer.py'.
- The 'Tests' option is removed from 'PR Type' in 'pr_custom_labels.toml'.
- The 'PR Type' is changed from array to string in 'pr_description_prompts.toml'.
- The 'PR Labels' key is added to 'pr_description_prompts.toml'.
- The 'PR Type' is changed from array to string and the 'PR Labels' key is removed in 'pr_reviewer_prompts.toml'.
___ …
> Refactoring PR Labels Handling and Display

- RELEASE_NOTES.md
- Usage.md
- docs/REVIEW.md
- pr_agent/git_providers/bitbucket_provider.py
- pr_agent/git_providers/git_provider.py
- pr_agent/git_providers/github_provider.py
- pr_agent/git_providers/gitlab_provider.py
- pr_agent/settings/configuration.toml
- pr_agent/tools/pr_reviewer.py
Enhancement
___
This PR introduces a new feature to the PR Agent, allowing it to publish persistent reviews. The main changes include:
- Added a new method `publish_persistent_review` in the abstract `git_provider` class and its implementations in `bitbucket_provider`, `github_provider`, and `gitlab_provider`.
- Updated the `run` method in `pr_reviewer` to use the new `publish_persistent_review` method based on the configuration.
- Updated the configuration file to include a new setting for enabling persistent comments.
- Updated the documentation and usage files to reflect these changes.
___
- `pr_agent/git_providers/bitbucket_provider.py`: Added a new method `publish_persistent_review` to update existing PR comments with the new review.
- …
> Add Persistent Review Feature to PR Agent

- pr_agent/agent/pr_agent.py
- pr_agent/cli.py
Bug fix
___
This PR introduces a fix for handling command line arguments that contain spaces in the pr_agent. The main changes include:
- Addition of a new function `handle_args_with_quotes` that processes the arguments and adds quotes around arguments that contain spaces.
- Modification of the `run` function to call the new `handle_args_with_quotes` function.
___
- `pr_agent/cli.py`: Added a new function `handle_args_with_quotes` to handle command line arguments with spaces. The `run` function is also updated to use this new function.
</details>
___
Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!
> Handling CLI Arguments with Quotes in pr_agent

- Usage.md
- pr_agent/algo/__init__.py
- pr_agent/algo/ai_handler.py
- pr_agent/settings/.secrets_template.toml
- requirements.txt
This PR adds support for Google's Vertex AI which is fairly simple as the litellm package just supports it.
I don't know if the way I dealt with the config is correct, at the moment it seems like everything else needs an Open AI key but obviously Vertex does not so I removed the attribute error check.
If you are open to accepting this PR then I'm happy to update documentation etc. as well.
> Support Google's Vertex AI

- .github/workflows/pr-agent-review.yaml
- RELEASE_NOTES.md
Enhancement
___
This PR introduces the following changes:
- Release of version 0.10 of the pr-agent, with various new features and bug fixes.
- Update to the GitHub workflow file to include a new environment variable.
___
- `.github/workflows/pr-agent-review.yaml`: Added a new environment variable 'GITHUB_ACTION.AUTO_REVIEW' to the GitHub workflow.
- `RELEASE_NOTES.md`: Updated the release notes for version 0.10, detailing new features, improvements and bug fixes.
</details>
> Version 0.10 Release and Workflow Update

- pr_agent/servers/serverless.py
Refactoring
___
This PR removes the unnecessary call to `setup_logger()` in the `serverless.py` file. The logger setup is already being handled within `github_app.py`, making the additional call in `serverless.py` redundant.
___
- `pr_agent/servers/serverless.py`: Removed the import and call to `setup_logger()`.
</details>
> Removal of Redundant Logger Setup

- INSTALL.md
- docker/Dockerfile
- pr_agent/git_providers/__init__.py
- pr_agent/git_providers/bitbucket_server_provider.py
- pr_agent/servers/bitbucket_server_webhook.py
- tests/unittest/test_bitbucket_provider.py
Hi all, this is an initial implementation that works on BitBucket Server and Data Center.
Just enable it on configuration.toml and
```toml
git_provider="bitbucket_server"
```
And:
python cli.py --pr_url https://git.onpreminstanceofbitbucket.com/projects/PROJECT/repos/REPO/pull-requests/1 review
> Added BitBucket Server and Data Center support

- Usage.md
- pr_agent/algo/__init__.py
- pr_agent/algo/ai_handler.py
- pr_agent/algo/utils.py
- pr_agent/settings/.secrets_template.toml
- requirements.txt
closes #459 
Added support for Anthropic Claude on Amazon Bedrock. I'll add some explanation in the review comments.
> Add Amazon Bedrock support

- pr_agent/git_providers/github_provider.py
enhancement
___
This PR enhances the functionality of the `github_provider.py` script to improve compatibility with GitHub Actions. The main change is the update of the `pr_url` assignment. Previously, the `pr_url` was directly assigned from the input argument. Now, if a pull request URL is provided and it contains 'pull', the script sets the pull request and the `last_commit_id`, and then retrieves the `pr_url` from the pull request object. This change is necessary because the `pr_url` for GitHub Actions can be in the form of `api.github.com`, so it's more reliable to get the URL directly from the pull request object.
___
- `pr_agent/git_providers/github_provider.py`: The `pr_url` assignment has been updated. If a pull request URL is provided and it …
> Enhance pr_url assignment in github_provider.py for GitHub Actions compatibility

- INSTALL.md
Documentation
___
This PR updates the documentation to include an additional step in the Lambda function setup process. The new step instructs users to specify the `AZURE_DEVOPS_CACHE_DIR` environment variable in the Lambda function to a writable location such as /tmp. This change is in response to issue #443.
___
- `INSTALL.md`: Added a new step in the Lambda function setup process instructing users to specify the `AZURE_DEVOPS_CACHE_DIR` environment variable to a writable location. The step numbering was also updated accordingly.
</details>
> Specify Cache Directory in Azure DevOps in Lambda Function Setup

- requirements.txt
enhancement
___
The current incarnation of pr-agent would not run using Python 3.12 - there were errors thrown by the some of the required packages.
This PR updates the versions of several packages in the requirements.txt file to be compatible with Python 3.12. The updated dependencies include:
- aiohttp from 3.8.4 to 3.9.1
- boto3 from 1.33.1 to 1.33.6
- dynaconf from 3.1.12 to 3.2.4
- PyYAML from 6.0 to 6.0.1
- tiktoken from 0.4.0 to 0.5.2
___
- `requirements.txt`: The versions of several dependencies have been updated to be compatible with Python 3.12.
</details>
> Update dependencies in requirements.txt for Python 3.12

- pr_agent/servers/bitbucket_server_webhook.py
- pr_agent/settings/.secrets_template.toml
- pr_agent/settings/configuration.toml
I improved the Bitbucket server to enable all commands like review, ask and so on... plus I added the missing webhook HMAC security check.
> feat: Improved server, security and commands

- pr_agent/algo/ai_handlers/openai_ai_handler.py
The deployment_id variable is assigned but never used in the function.
> Remove unused deployment_id variable.

- pr_agent/git_providers/github_provider.py
- pr_agent/tools/ticket_pr_compliance_check.py
- tests/unittest/test_fetching_sub_issues.py
**Summary**
This PR improves the ticket compliance tool by ensuring that sub-issues and their content are also collected when analyzing a pull request. Previously, the tool only gathered the main issue's body, potentially missing important context from sub-issues (Look at Issue #1499)
This implementation uses GitHub’s GraphQL API to fetch sub-issues recursively and extract their content for better analysis.
**Changes Introduced**
- Updated extract_ticket_links_from_pr_description
- Now fetches sub-issues linked to an issue.
- Recursively retrieves sub-issues using GraphQL API.
- [Stores both main issue content and sub-issue content.
- Added Unit Tests (test_fetching_sub_issues.py)
- Tests fetching sub-issues for a known GitHub issue.
- Ensures the system correctly retrieves sub-issue …
> Added sub-issue fetching to enhance PR analysis
